/**
 * Portfolio copy and links — edit this file to update the whole site.
 * Resume PDFs live in `site/public/`.
 */

export const site = {
  name: "Brian Bales",
  /** Shown in the nav bar (keep short). */
  navBrand: "Brian Bales",
  role: "Software Engineer",

  documentTitle: "Brian Bales | Software Engineer",

  resume: {
    /** Default / nav shortcut — one-page version. */
    publicPath: "/Brian_Bales_2026_Resume_1page.pdf",
    buttonLabel: "Download resume",
    onePage: {
      publicPath: "/Brian_Bales_2026_Resume_1page.pdf",
      buttonLabel: "1-page resume",
    },
    twoPage: {
      publicPath: "/Brian_Bales_2026_Resume_2page.pdf",
      buttonLabel: "2-page resume",
    },
  },

  links: {
    github: "https://github.com/brianbales99",
    linkedin: "https://www.linkedin.com/in/brianbales99",
    email: "mailto:Brianbales99@gmail.com",
    twitter: "",
  },

  home: {
    statusBadge: "Open to opportunities",
    headline: {
      line1: "Building",
      accent: "production-ready",
      line2: "software systems.",
    },
    intro:
      "Software Engineer in Los Angeles, CA focused on internal production tools, SaaS integrations, workflow automation, and AI-powered applications.",
    portraitSrc: "/portrait.png",
    portraitAlt: "Brian Bales — professional photo",

    summarySection: {
      eyebrow: "Professional summary",
      title: "SUMMARY",
      body: "Software Engineer with experience building internal production tools, full-stack SaaS applications, and AI-powered workflows across entertainment and enterprise environments. Skilled in React, JavaScript/TypeScript, Python, Node.js, SQL, REST APIs, and cloud platforms. Proven ability to partner with business stakeholders, translate operational needs into technical solutions, troubleshoot integrations, and rapidly learn new platforms.",
    },

    techSection: {
      eyebrow: "Core skills",
      title: "TECH_STACK",
      metaLine: "// From my resume",
      cards: [
        {
          n: "01",
          icon: "terminal",
          title: "Enterprise Automation",
          description:
            "Oracle SFP workflows using Groovy + SQL for reliable financial aid logic.",
          border: "border-primary",
          iconClass: "text-primary",
          hoverClass: "group-hover:text-primary",
        },
        {
          n: "02",
          icon: "database",
          title: "Salesforce Delivery",
          description:
            "Lightning Web Components + Apex and data integrations with Salesforce Playbook.",
          border: "border-secondary",
          iconClass: "text-secondary",
          hoverClass: "group-hover:text-secondary",
        },
        {
          n: "03",
          icon: "cloud",
          title: "React + UX Systems",
          description:
            "React UIs with efficient filtering and integrations (including Linear task dashboards).",
          border: "border-tertiary",
          iconClass: "text-tertiary",
          hoverClass: "group-hover:text-tertiary",
        },
        {
          n: "04",
          icon: "auto_awesome",
          title: "AI Tools & Workflows",
          description:
            "Cursor, MCP, agents, custom Skills, and prompt engineering for AI-assisted delivery.",
          border: "border-primary",
          iconClass: "text-primary",
          hoverClass: "group-hover:text-primary",
        },
      ],
      chips: [
        "TypeScript",
        "React",
        "Python",
        "Node.js",
        "SQL",
        "Cursor",
        "MCP",
        "Salesforce",
        "Supabase",
        "Flutter",
      ],
      skills: [
        {
          title: "Languages",
          icon: "code",
          tone: "primary",
          items: [
            "JavaScript",
            "TypeScript",
            "Python",
            "SQL",
            "Groovy",
            "Java",
            "C++",
            "HTML/CSS",
          ],
        },
        {
          title: "Frontend & Mobile",
          icon: "developer_mode_tv",
          tone: "tertiary",
          items: [
            "React",
            "Angular",
            "Next.js",
            "Vue.js",
            "Flutter",
            "Lightning Web Components",
            "Material UI",
          ],
        },
        {
          title: "Backend & Integration",
          icon: "hub",
          tone: "secondary",
          items: [
            "Node.js",
            "Express",
            "REST APIs",
            "Supabase",
            "Firebase/Firestore",
            "PostgreSQL",
            "Authentication",
            "API integrations",
          ],
        },
        {
          title: "AI & Developer Tools",
          icon: "auto_awesome",
          tone: "primary",
          items: [
            "Cursor",
            "Claude",
            "GitHub Copilot",
            "Google Stitch",
            "Model Context Protocol (MCP)",
            "AI agents",
            "Custom rules & Skills",
            "Prompt engineering",
            "Replicate",
            "Fal.AI",
          ],
        },
        {
          title: "Platforms & Data",
          icon: "build",
          tone: "secondary",
          items: [
            "Salesforce",
            "Vercel",
            "Fly.io",
            "Git/GitHub",
            "Jira",
            "Figma",
            "scikit-learn",
            "TensorFlow",
            "NumPy",
            "Pandas",
            "Matplotlib",
          ],
        },
        {
          title: "AI-Assisted Workflows",
          icon: "account_tree",
          tone: "tertiary",
          items: [
            "Cursor + MCP integrations",
            "Project-specific rules",
            "Reusable Skills & agents",
            "Stitch design-to-code handoffs",
            "Manual architecture validation",
            "Security & API review",
          ],
        },
      ],
    },

    experienceSection: {
      eyebrow: "Work Experience",
      title: "EXPERIENCE",
      metaLine: "From my resume",
      items: [
        {
          id: "handshake-ai-contract",
          company: "Handshake AI",
          role: "AI Engineer (Contract)",
          location: "Remote",
          range: "January 2026 - Present",
          bullets: [
            "Evaluate frontier AI model outputs across coding and technical reasoning tasks, assessing accuracy, logic, instruction-following, completeness, and edge cases.",
            "Create structured technical feedback and response-validation workflows that help improve model quality and reliability.",
            "Apply software engineering judgment to identify faulty assumptions, implementation defects, and unsafe or unsupported conclusions in AI-generated responses.",
          ],
        },
        {
          id: "fox-ent-production-post",
          company: "FOX Entertainment",
          role: "Software Engineer",
          location: "Los Angeles, CA",
          range: "February 2025 - May 2025",
          bullets: [
            "Developed React-based internal applications supporting production workflows across shows, episodes, and deliveries; rapidly iterated UI/UX with stakeholders using AI-assisted development tools.",
            "Built a full-stack integration connecting Linear task data to custom frontend interfaces, giving production teams clearer visibility into work status and operational progress.",
            "Engineered scalable filtering and navigation components for large production datasets, reducing friction when locating operational content.",
            "Partnered with production and technical teams to translate workflow pain points into practical features used by internal users.",
          ],
        },
        {
          id: "fox-corp-business-data",
          company: "FOX Corporation",
          role: "Software Developer",
          location: "Los Angeles, CA",
          range: "September 2024 - December 2024",
          bullets: [
            "Developed Salesforce Playbook tools for production scheduling and crew coordination using JavaScript, Lightning Web Components, Apex, and HTML/CSS.",
            "Integrated crew availability, project workload, and scheduling data into a unified SaaS workflow to improve production coordination.",
            "Collaborated with engineers, product managers, and business stakeholders in Agile environments to refine requirements, test changes, and deliver platform enhancements.",
            "Quickly learned Salesforce platform development and applied web engineering fundamentals to custom interfaces, backend logic, and workflow automation.",
          ],
        },
        {
          id: "highstreet-oracle-sfp",
          company: "Highstreet IT Solutions",
          role: "Software Developer",
          location: "Rockville, MD",
          range: "May 2021 - December 2022",
          bullets: [
            "Configured and customized Oracle Student Financial Planning services supporting financial aid workflows for 1,000+ university students.",
            "Developed backend workflow logic using Groovy and SQL to automate eligibility checks, award processing, and financial aid operations.",
            "Troubleshot data and system issues across interconnected workflows, improving process accuracy and reliability for administrators and students.",
            "Partnered with financial aid stakeholders to translate policy and operational requirements into tested enterprise-system updates.",
          ],
        },
      ],
    },

    educationSection: {
      eyebrow: "Schooling",
      title: "EDUCATION",
      metaLine: "Degrees",
      items: [
        {
          id: "csun-bs-cs",
          school: "California State University, Northridge",
          degree: "B.S. Computer Science",
        },
        {
          id: "csun-ms-se",
          school: "California State University, Northridge",
          degree: "M.S. Software Engineering",
        },
      ],
    },

    certifications: {
      eyebrow: "Licenses & certifications",
      title: "Salesforce Certified AI Associate",
      items: [
        {
          imageSrc: "/ai-associate.png",
          imageAlt: "Salesforce Certified AI Associate credential image",
          issuer: "Salesforce",
          issued: "Issued Nov 2024",
          credentialId: "Credential ID: 5272615",
          verifyUrl:
            "https://trailhead.salesforce.com/en/credentials/aiassociate",
        },
      ],
    },

    aboutSection: {
      eyebrow: "About me",
      title: "OFF THE CLOCK",
      blurb:
        "A few things I’m usually into when I’m not coding (and yes, they absolutely influence my side projects).",
      items: [
        {
          id: "about-basketball",
          icon: "sports_basketball",
          title: "Basketball (Lakers fan)",
          body: "I’m a huge Lakers and Kobe fan, and basketball has been part of my life since I was growing up. I played a lot as a kid, so watching a big Lakers game still feels personal to me, especially when the crowd gets loud and the game gets close.",
          tone: "primary",
          imageSrc: "/about-basketball.png",
          imageAlt: "Lakers game arena view",
        },
        {
          id: "about-golf",
          icon: "golf_course",
          title: "Golf",
          body: "I picked up golf in 2020 and got really into it for a stretch. I don’t play as much right now, but I still enjoy it, and one of my favorite courses is Rustic Canyon. If you need golf lessons, call me... but you might end up playing worse.",
          tone: "tertiary",
          imageSrc: "/about-golf.png",
          imageAlt: "Brian golfing on a course",
        },
        {
          id: "about-trading-cards",
          icon: "style",
          title: "Trading cards",
          body: "I like collecting cards across every sport, but basketball is definitely my main focus. I’m into the full hobby side of it, from individual cards to wax (sealed boxes), and that collector mindset is exactly what inspired me to build card-related side projects.",
          tone: "secondary",
          imageSrc: "/about-trading-cards.png",
          imageAlt: "Graded basketball card collection",
        },
        {
          id: "about-shoes",
          icon: "footprint",
          title: "Sneakers & streetwear",
          body: "I’ve collected streetwear pieces and concert shirts since I was 18, and sneakers have always been a big part of that. One of my all-time favorite pairs is the Kobe 11 FTB — timeless look, great details, and still one of the cleanest Kobe models to me.",
          tone: "primary",
          imageSrc: "/about-sneakers.png",
          imageAlt: "Kobe 11 FTB sneaker",
        },
      ],
    },
  },

  projects: {
    eyebrow: "Selected work",
    titleLine: "PROJECTS &",
    titleAccent: "PORTFOLIO",
    blurb:
      "Representative engineering work that shows how I design, build, and deliver reliable systems end-to-end.",
    statusLine: "Status: Open to full-time roles",
    items: [
      {
        slug: "dreamcatcher",
        title: "Dreamcatcher",
        description:
          "Currently in development — a full-stack mobile application that uses AI to generate dream interpretations and personalized visual dream experiences.",
        category: "featured",
        image: "/dreamcatcher-thumb.svg",
        imageAlt: "Dreamcatcher sleeping sheep logo",
        tags: ["AI", "Mobile", "Full-Stack", "In Progress"],
        icon: "bedtime",
        iconTone: "secondary",
        demoUrl: "https://github.com/brianbales99/Dreamcatcher",
        demoLabel: "Open Repo",
        extraButtonLabel: "",
        extraButtonUrl: "",
        extraButtonTarget: "_blank",
        previewImage: "",
        previewImageAlt: "",
        sourceUrl: "https://github.com/brianbales99/Dreamcatcher",
        sourceLabel: "Source",
      },
      {
        slug: "ai-flutter",
        title: "Pixloo.AI: ai_flutter",
        description:
          "This is Pixloo.AI / AI Creator, a Flutter app that lets users generate images from text prompts and create animations from images with a modern, mobile-first UI. It includes login/onboarding plus billing & usage tracking (credits, purchase history) and integrates services like Supabase (auth/backend) with optional in-app purchases and ads.",
        category: "featured",
        image: "/pixloo-thumb.png",
        imageAlt: "Pixloo.AI app icon",
        tags: ["Flutter", "Dart", "AI", "Phone App"],
        icon: "developer_mode_tv",
        iconTone: "tertiary",
        demoUrl: "https://github.com/brianbales99/ai_flutter",
        demoLabel: "Open Repo",
        extraButtonLabel: "Download it here",
        extraButtonUrl: "__MODAL_PIXLOO_DOWNLOAD__",
        extraButtonTarget: "_self",
        previewImage: "/pixloo-preview.png",
        previewImageAlt: "Pixloo.AI app screenshot preview",
        sourceUrl: "https://github.com/brianbales99/ai_flutter",
        sourceLabel: "Source",
      },
      {
        slug: "personal-portfolio-repo",
        title: "Personal-Portfolio",
        description:
          "This is my personal web page built to showcase my work as a software engineer—projects, publications, and a live resume—using a fast React + TypeScript stack with a clean, modern UI and easy-to-update content.",
        category: "featured",
        image: "/personal-portfolio.png",
        imageAlt: "Personal portfolio screenshot",
        tags: ["React", "TypeScript", "UI", "Web App"],
        icon: "terminal",
        iconTone: "primary",
        demoUrl: "https://github.com/brianbales99/Personal-Portfolio",
        demoLabel: "Open Repo",
        extraButtonLabel: "Link",
        extraButtonUrl: "/",
        extraButtonTarget: "_self",
        previewImage: "",
        previewImageAlt: "",
        sourceUrl: "https://github.com/brianbales99/Personal-Portfolio",
        sourceLabel: "Source",
      },
      {
        slug: "trading-card-generator",
        title: "Trading Card Generator",
        description:
          "Fun automation project that takes a trading card, generates an AI background based on the card’s description + features using top image AI models, and produces an Instagram-ready caption you can post right away.",
        category: "featured",
        image: "/trading-card-generator.png",
        imageAlt: "Trading card generator preview",
        tags: ["AI", "Automation", "Content", "Script"],
        icon: "auto_awesome",
        iconTone: "secondary",
        demoUrl: "https://github.com/brianbales99/trading-card-generator",
        demoLabel: "Open Repo",
        extraButtonLabel: "",
        extraButtonUrl: "",
        extraButtonTarget: "_blank",
        previewImage: "",
        previewImageAlt: "",
        sourceUrl: "https://github.com/brianbales99/trading-card-generator",
        sourceLabel: "Source",
      },
      {
        slug: "ga-sfs-machine-learning",
        title: "Machine Learning GA-SFS",
        description:
          "GA-SFS: a two-stage hybrid algorithm for feature selection in biomedical data (Genetic Algorithms + Sequential Forward Selection).",
        category: "research",
        image: "/ml-ga-sfs.png",
        imageAlt: "GA-SFS master research thumbnail",
        tags: ["Python", "Feature Selection", "Biomedical ML"],
        icon: "analytics",
        iconTone: "secondary",
        demoUrl:
          "https://github.com/brianbales99/Machine-Learning-GA-SFS-A-Two-Stage-Hybrid-Algorithm-for-Feature-Selection-in-Biomedical-Data",
        demoLabel: "Open Repo",
        extraButtonLabel: "Read it here",
        extraButtonUrl: "/publications",
        extraButtonTarget: "_self",
        previewImage: "",
        previewImageAlt: "",
        sourceUrl:
          "https://github.com/brianbales99/Machine-Learning-GA-SFS-A-Two-Stage-Hybrid-Algorithm-for-Feature-Selection-in-Biomedical-Data",
        sourceLabel: "Source",
      },

      {
        slug: "cocktail-webapp",
        title: "Cocktail WebApp",
        description:
          "JavaScript web app project for browsing and managing cocktail-related content/UI.",
        category: "school",
        image: "/cocktail-webapp.png",
        imageAlt: "Cocktail WebApp screenshot",
        tags: ["JavaScript", "Web App"],
        icon: "code",
        iconTone: "primary",
        demoUrl: "https://github.com/fvargas320/CocktailWebApp",
        demoLabel: "Open Repo",
        extraButtonLabel: "",
        extraButtonUrl: "",
        extraButtonTarget: "_blank",
        previewImage: "",
        previewImageAlt: "",
        sourceUrl: "https://github.com/fvargas320/CocktailWebApp",
        sourceLabel: "Source",
      },
      {
        slug: "careconnect",
        title: "CareConnect",
        description:
          "CareConnect project (Comp 583). Web app for connecting people and streamlining care workflows.",
        category: "school",
        image: "/careconnect-scheduling.svg",
        imageAlt: "Doctor scheduling UI thumbnail",
        tags: ["JavaScript", "App", "Care"],
        icon: "hub",
        iconTone: "tertiary",
        demoUrl: "https://github.com/brianbales99/CareConnect",
        demoLabel: "Open Repo",
        extraButtonLabel: "",
        extraButtonUrl: "",
        extraButtonTarget: "_blank",
        previewImage: "",
        previewImageAlt: "",
        sourceUrl: "https://github.com/brianbales99/CareConnect",
        sourceLabel: "Source",
      },
      {
        slug: "university-map-quiz",
        title: "University Map Quiz",
        description:
          "Campus knowledge game that tests navigation and recognition across CSUN locations.",
        category: "school",
        image: "/university-map-quiz.png",
        imageAlt: "University Map Quiz screenshot",
        tags: ["JavaScript", "HTML/CSS", "Game"],
        icon: "map",
        iconTone: "secondary",
        demoUrl:
          "https://github.com/brianbales99/University-Map-Quiz-Comp484",
        demoLabel: "Open Repo",
        extraButtonLabel: "",
        extraButtonUrl: "",
        extraButtonTarget: "_blank",
        previewImage: "",
        previewImageAlt: "",
        sourceUrl:
          "https://github.com/brianbales99/University-Map-Quiz-Comp484",
        sourceLabel: "Source",
      },
      {
        slug: "todo-list-app",
        title: "Todo_List_App",
        description:
          "Flutter todo CRUD app with Firebase integration for task creation, updates, and deletion.",
        category: "school",
        image: "/todo-list.png",
        imageAlt: "Todo List App screenshot",
        tags: ["Flutter", "Firebase", "CRUD"],
        icon: "checklist",
        iconTone: "tertiary",
        demoUrl: "https://github.com/brianbales99/Todo_List_App",
        demoLabel: "Open Repo",
        extraButtonLabel: "",
        extraButtonUrl: "",
        extraButtonTarget: "_blank",
        previewImage: "",
        previewImageAlt: "",
        sourceUrl: "https://github.com/brianbales99/Todo_List_App",
        sourceLabel: "Source",
      },
      {
        slug: "news-to-you",
        title: "NewsToYou",
        description:
          "Dart project for building a news UI experience (NewsToYou).",
        category: "school",
        image: "/iphone-basic.svg",
        imageAlt: "iPhone app thumbnail",
        tags: ["Dart", "UI", "News"],
        icon: "article",
        iconTone: "primary",
        demoUrl: "https://github.com/Benten559/NewsToYou",
        demoLabel: "Open Repo",
        extraButtonLabel: "",
        extraButtonUrl: "",
        extraButtonTarget: "_blank",
        previewImage: "",
        previewImageAlt: "",
        sourceUrl: "https://github.com/Benten559/NewsToYou",
        sourceLabel: "Source",
      },
    ],
  },

  publications: {
    archiveLabel: "PUBLICATIONS",
    title: "Publications & Research",
    totalEntries: 2,
    lastUpdate: "2025_Q2",
    filterChips: ["ALL_RESEARCH", "FEATURE_SELECTION", "BIOMEDICAL_DATA"],
    items: [
      {
        id: "pub-ga-sfs-ieee",
        kindLabel: "IEEE Publication",
        date: "2025",
        title:
          "GA-SFS: A Two-Stage Hybrid Algorithm for Feature Selection in Biomedical Data",
        abstract:
          "GA-SFS combines Genetic Algorithms (global exploration) with Sequential Forward Selection (subset refinement) to improve classification accuracy while reducing redundant or irrelevant features in high-dimensional biomedical datasets. Across cancer datasets, GA-SFS reduces feature redundancy by over 50%, improving robustness and interpretability.",
        tags: ["FEATURE_SELECTION", "HYBRID_ALGORITHM", "BIOMEDICAL_DATA"],
        accent: "primary",
        side: { label: "Downloads", value: "124+" },
        pdfUrl: "https://ieeexplore.ieee.org/document/10903702/",
        pdfLabel: "Open IEEE page",
        instantPdfUrl: "/ieee-publication.pdf",
      },
      {
        id: "pub-ga-sfs-thesis",
        kindLabel: "M.S. Thesis | CSU ScholarWorks",
        date: "May 22, 2025",
        title:
          "GA-SFS: A Two-Stage Hybrid Algorithm for Feature Selection in Biomedical Data",
        abstract:
          "This thesis studies feature selection in biomedical data: redundant and irrelevant features can harm generalization and increase computation. GA-SFS pairs Genetic Algorithms with Sequential Forward Selection to efficiently search and refine informative feature subsets, aiming for improved performance with reduced redundancy and better interpretability.",
        tags: ["FEATURE_SELECTION", "M.S. THESIS", "BIOMEDICAL_DATA"],
        accent: "secondary",
        side: { label: "Access", value: "Public PDF page" },
        pdfUrl: "https://scholarworks.calstate.edu/concern/theses/vt150v25b",
        pdfLabel: "Open thesis (PDF page)",
        instantPdfUrl: "/thesis.pdf",
      },
    ],
    contact: {
      title: "Hiring or questions?",
      body:
        "Email is the fastest way to reach me at Brianbales99@gmail.com. You can also download my 1-page or 2-page resume from the home page.",
    },
  },
} as const;

export type Site = typeof site;
